blank_issues_enabled: false
contact_links:
  - name: Contributing Guide
    url: https://git.jbnco.co/npub1v89nr2zax8ef0ceyu9te0sjyqv3newa3e82m0rd4kye3ekeyhv2sqf30cc/corkboards/blob/main/CONTRIBUTING.md
    about: Read the contributing guide before opening an issue
