export const TIPS = [
  'Tip: Save notes with the green buttons and dismiss notes with the red buttons to keep your feed clean.',
  'Tip: Click "Consolidate" in the status bar to collapse blank spaces after dismissing.',
  'Tip: Create custom corkboards to group follows by topic or interest.',
  'Tip: Use the kind filter toggles to show only replies, reposts, or original posts.',
  'Tip: The Discover tab finds notes your friends engage with from people you don\'t follow.',
  'Tip: Your settings are encrypted and backed up to Blossom servers — log in anywhere and restore.',
  'Tip: You can follow someone directly from their Discover card — click the button below their avatar.',
  'Tip: You can use your same login credentials to use the same account on lots of different websites. See a list of just a few at https://nostrapps.com/',
  'Tip: Nostr is very versatile, and so are your login credentials. Find out more at https://nostr.how/en/what-is-nostr',
  'Tip: Use the Discover tab to branch out. Curate your experience carefully and your feeds will accentuate your life.',
  'Tip: No more doom scrolling. With care, you can build your own corkboards with people who add to your experience, rather than detract from it.',
  'Tip: Zap notes you appreciate — it sends real bitcoin to the author as a thank you.',
  'Tip: You own your identity on Nostr. No company can ban you, shadow you, or take your account away.',
  'Tip: Your nsec key is like a master password — never share it with anyone or paste it into untrusted sites.',
  'Tip: Corkboards sync across devices. Log in on your phone and your desktop and everything stays in sync.',
  'Tip: Use the thread view to follow conversations — click any note to see the full discussion.',
  'Tip: You can repost a note to share it with your followers, or quote it to add your own commentary.',
  'Tip: Your follow list is stored on Nostr, not on any single app. Switch apps anytime without losing your network.',
  'Tip: Browser extensions like Alby, Ditto Signer, or nos2x can manage your keys more securely than pasting an nsec.',
  'Tip: Every note on Nostr is cryptographically signed — nobody can forge a post in your name without having your nsec.',
  'Tip: Corkboards are private to you. Only you can see how you\'ve organized your feeds.',
  'Tip: You can add npubs to custom corkboards directly, you don\'t have to follow to see notes.',
  'Tip: Notes on Nostr can include images, video, links, files, and even live games and more — they\'re richer than they first appear.',
  'Tip: You can back up your settings as a local file from the settings menu for extra safety.',
];
